server:
  port: 8185
#spring:
#  r2dbc:
#    url: r2dbc:h2:file:////data/h2db/localhost
spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: root
    password: root
#    url: jdbc:h2:file:/data/h2db/localhost
    url: jdbc:h2:file:~/.h2/localhost
  h2:
    console:
      enabled: true
      settings:
        trace: true
        web-allow-others: true
      path: /h2-console
  sql:
    init:
      schema-locations: classpath:schema.sql
      mode: always
mybatis-plus:
  configuration:
    cache-enabled: false
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/*.xml
